version: '3.8'

services:
  # web:
  #   image: nginx:latest
  #   ports:
  #     - 8080:80

  database:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
